theme: jekyll-theme-cayman
title: Domenico Cotroneo
description: [Department of Electrical Engineering and Information Technology](http://www.dieti.unina.it). Università degli studi di Napoli Federico II
